CREATE TABLE LOGIN_DETAILS(
LOGIN_ID NUMBER(10),
PASSWORD VARCHAR(20)NOT NULL,
ROLE VARCHAR(20)NOT NULL,
CONSTRAINT PK_LOGIN_ID PRIMARY KEY(LOGIN_ID)
);

CREATE SEQUENCE seq_login_details INCREMENT by 1 Start with 400;
drop SEQUENCE seq_login_details;


INSERT INTO LOGIN_DETAILS(LOGIN_ID,PASSWORD,ROLE) VALUES(seq_login_details.NEXTVAL,'PASS1001','DIRECTOR');
INSERT INTO LOGIN_DETAILS(LOGIN_ID,PASSWORD,ROLE) VALUES(seq_login_details.NEXTVAL,'PASS1002','MANAGER');
INSERT INTO LOGIN_DETAILS(LOGIN_ID,PASSWORD,ROLE) VALUES(seq_login_details.NEXTVAL,'PASS1003','DEVELOPER');
INSERT INTO LOGIN_DETAILS(LOGIN_ID,PASSWORD,ROLE) VALUES(seq_login_details.NEXTVAL,'PASS1004','AGENT');
INSERT INTO LOGIN_DETAILS(LOGIN_ID,PASSWORD,ROLE) VALUES(seq_login_details.NEXTVAL,'PASS1005','MANAGER');
INSERT INTO LOGIN_DETAILS(LOGIN_ID,PASSWORD,ROLE) VALUES(seq_login_details.NEXTVAL,'PASS1006','DEVELOPER');

--------------------------------------------------------------------
CREATE TABLE EMPLOYEE_DETAILS(
EMPLOYEE_ID NUMBER(10),
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
ADDRESS VARCHAR(50),
MANAGER_ID NUMBER(10),
CITY VARCHAR(20),
STATE VARCHAR(20),
EMAIL_ID VARCHAR(50),
CONTACT_NO VARCHAR(10),
DESIGNATION VARCHAR(20),
LOGIN_ID NUMBER(10),
CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY(EMPLOYEE_ID),
CONSTRAINT FK_LOGIN_ID FOREIGN KEY(LOGIN_ID)
REFERENCES LOGIN_DETAILS(LOGIN_ID)
);
CREATE SEQUENCE sequ_employee_details INCREMENT by 1 Start with 500;
drop SEQUENCE sequ_employee_details;

INSERT INTO employee_details(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,ADDRESS,MANAGER_ID,
CITY,STATE,EMAIL_ID,CONTACT_NO,DESIGNATION,LOGIN_ID) VALUES
(sequ_employee_details.NEXTVAL,'SANTOSH','HONRAO','KANJURMARG',0,'MUMBAI','MAHARASHTRA',
'SANTOSH123@gmail.com',9875468745,'DIRECTOR',400);

INSERT INTO employee_details(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,ADDRESS,MANAGER_ID,
CITY,STATE,EMAIL_ID,CONTACT_NO,DESIGNATION,LOGIN_ID) VALUES
(sequ_employee_details.NEXTVAL,'MAHIMA','DUBEY','KALYAN',500,'MUMBAI','MAHARASHTRA',
'SANTOSH123@gmail.com',9875468745,'MANAGER',401);

INSERT INTO employee_details(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,ADDRESS,MANAGER_ID,
CITY,STATE,EMAIL_ID,CONTACT_NO,DESIGNATION,LOGIN_ID) VALUES
(sequ_employee_details.NEXTVAL,'ROHIT','THAKUR','KALYAN',500,'THANE','MAHARASHTRA',
'ROHIT123@gmail.com',8798754654,'MANAGER',404);


INSERT INTO employee_details(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,ADDRESS,MANAGER_ID,
CITY,STATE,EMAIL_ID,CONTACT_NO,DESIGNATION,LOGIN_ID) VALUES
(sequ_employee_details.NEXTVAL,'SANIKA','MANCHEKAR','THANE',501,'THANE','MAHARASHTRA',
'SANIKA123@gmail.com',8897854654,'DEVELOPER',402);


INSERT INTO employee_details(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,ADDRESS,MANAGER_ID,
CITY,STATE,EMAIL_ID,CONTACT_NO,DESIGNATION,LOGIN_ID) VALUES
(sequ_employee_details.NEXTVAL,'MERAJ','SHAIKH','MUMBAI',502,'MUMBAI','MAHARASHTRA',
'MERAJ23@gmail.com',9987548684,'DEVELOPER',405);



------------------------------------------------------------
CREATE TABLE SLAB_MASTER(
SLAB_MASTER_ID NUMBER(10),
DESIGNATION VARCHAR(20),
SLAB NUMBER(6),
TRAVEL_MODE VARCHAR(20),
CONSTRAINT PK_SLAB_MASTER_ID PRIMARY KEY(SLAB_MASTER_ID)
);

CREATE SEQUENCE seq_slab_master INCREMENT by 1 Start with 600;
drop SEQUENCE seq_slab_master;

INSERT INTO slab_master(SLAB_MASTER_ID,DESIGNATION,SLAB,TRAVEL_MODE )
VALUES(seq_slab_master.NEXTVAL,'DIRECTOR',25000,'FLIGHT');
INSERT INTO slab_master(SLAB_MASTER_ID,DESIGNATION,SLAB,TRAVEL_MODE )
VALUES(seq_slab_master.NEXTVAL,'MANAGER',15000,'TRAIN');
INSERT INTO slab_master(SLAB_MASTER_ID,DESIGNATION,SLAB,TRAVEL_MODE )
VALUES(seq_slab_master.NEXTVAL,'DEVELOPER',10000,'TRAIN');
-----------------------------------------------------------------
CREATE SEQUENCE SEQUE_TRAVELLING_DETAILS INCREMENT by 1 Start with 800;
drop SEQUENCE SEQUE_TRAVELLING_DETAILS;
CREATE TABLE TRAVELLING_DETAILS(
TRAVEL_DETAILS_ID NUMBER(10) ,
HOTEL_NAME VARCHAR2(30),
HOTEL_ADDRESS VARCHAR2(20),
HOTEL_BOOKING_STATUS VARCHAR(10) NOT NULL,
TRAVEL_DEPARTURE_DATE DATE,
TRAVEL_RETURN_DATE DATE,
TICKET_BOOKING_STATUS VARCHAR(20),
ACCOMODATION_COST NUMBER(10),
CONSTRAINT PK_TRAVEL_DETAILS_ID PRIMARY KEY(TRAVEL_DETAILS_ID)
);
ALTER TABLE TRAVELLING_DETAILS MODIFY HOTEL_ADDRESS VARCHAR(50);

INSERT INTO TRAVELLING_DETAILS(TRAVEL_DETAILS_ID,HOTEL_NAME ,HOTEL_ADDRESS,HOTEL_BOOKING_STATUS,
TRAVEL_DEPARTURE_DATE ,TRAVEL_RETURN_DATE ,TICKET_BOOKING_STATUS ,ACCOMODATION_COST )
VALUES (SEQUE_TRAVELLING_DETAILS.NEXTVAL,'TAJ','MUMBAI','CONFIRMED',TO_DATE('12-Jan-2022','DD-MM-YYYY'),TO_DATE('14-Jan-2022','DD-MM-YYYY'),
'PENDING',10000);

INSERT INTO TRAVELLING_DETAILS(TRAVEL_DETAILS_ID,HOTEL_NAME ,HOTEL_ADDRESS,HOTEL_BOOKING_STATUS,
TRAVEL_DEPARTURE_DATE ,TRAVEL_RETURN_DATE ,TICKET_BOOKING_STATUS ,ACCOMODATION_COST )
VALUES (SEQUE_TRAVELLING_DETAILS.NEXTVAL,'TAJ','BANGLORE','CONFIRMED',TO_DATE('16-Jan-2022','DD-MM-YYYY'),TO_DATE('20-Jan-2022','DD-MM-YYYY'),
'PENDING',12000);


INSERT INTO TRAVELLING_DETAILS(TRAVEL_DETAILS_ID,HOTEL_NAME ,HOTEL_ADDRESS,HOTEL_BOOKING_STATUS,
TRAVEL_DEPARTURE_DATE ,TRAVEL_RETURN_DATE ,TICKET_BOOKING_STATUS ,ACCOMODATION_COST )
VALUES (SEQUE_TRAVELLING_DETAILS.NEXTVAL,'TAJ','CHENNAI','CONFIRMED',TO_DATE('12-Jan-2022','DD-MM-YYYY'),TO_DATE('14-Jan-2022','DD-MM-YYYY'),
'PENDING',15000);

INSERT INTO TRAVELLING_DETAILS(TRAVEL_DETAILS_ID,HOTEL_NAME ,HOTEL_ADDRESS,HOTEL_BOOKING_STATUS,
TRAVEL_DEPARTURE_DATE ,TRAVEL_RETURN_DATE ,TICKET_BOOKING_STATUS ,ACCOMODATION_COST )
VALUES (SEQUE_TRAVELLING_DETAILS.NEXTVAL,'TAJ','BANGLORE','CONFIRMED',TO_DATE('16-Jan-2022','DD-MM-YYYY'),TO_DATE('20-Jan-2022','DD-MM-YYYY'),
'PENDING',16000);
-----------------------------------------------------------
CREATE TABLE TRAVEL_AGENT_DETAILS(
TRAVLE_AGENT_ID NUMBER(10) ,
TRAVEL_AGENT_NAME VARCHAR(50),
SLAB_MASTER_ID NUMBER(10),
LOGIN_ID NUMBER(10),
CONSTRAINT PK_TRAVLE_AGENT_ID PRIMARY KEY(TRAVLE_AGENT_ID),
CONSTRAINT FK_SLAB_MASTER_ID FOREIGN KEY(SLAB_MASTER_ID)
REFERENCES SLAB_MASTER(SLAB_MASTER_ID),
CONSTRAINT FK_LOGIN_ID_NEW FOREIGN KEY(LOGIN_ID)
REFERENCES LOGIN_DETAILS(LOGIN_ID)
);
CREATE SEQUENCE seq_travel_agent_details INCREMENT by 1 Start with 1000;
drop SEQUENCE seq_travel_agent_details;
INSERT INTO TRAVEL_AGENT_DETAILS(TRAVLE_AGENT_ID,TRAVEL_AGENT_NAME,SLAB_MASTER_ID,LOGIN_ID)
VALUES(seq_travel_agent_details.NEXTVAL,'RAVI',600,400);
INSERT INTO TRAVEL_AGENT_DETAILS(TRAVLE_AGENT_ID,TRAVEL_AGENT_NAME,SLAB_MASTER_ID,LOGIN_ID)
VALUES(seq_travel_agent_details.NEXTVAL,'RAVI',601,401);
INSERT INTO TRAVEL_AGENT_DETAILS(TRAVLE_AGENT_ID,TRAVEL_AGENT_NAME,SLAB_MASTER_ID,LOGIN_ID)
VALUES(seq_travel_agent_details.NEXTVAL,'SANIKA',602,402);
------------------------------
CREATE TABLE TRAVEL_DOCUMENTS_DETAILS(
DOCUMENT_ID NUMBER(10) ,
DOCUMENT_TYPE VARCHAR(50) NOT NULL,
DOCUMENT_NAME VARCHAR(50) NOT NULL,
DOCUMENT_FILE BLOB,
CONSTRAINT PK_DOCUMENT_ID PRIMARY KEY(DOCUMENT_ID)
);

 CREATE SEQUENCE sequ_travel_document_details INCREMENT by 1 Start with 700;
 drop SEQUENCE sequ_travel_document_details ;

INSERT INTO travel_documents_details(DOCUMENT_ID,DOCUMENT_TYPE ,DOCUMENT_NAME
) VALUES (sequ_travel_document_details.NEXTVAL,'PDF','ADHAR CARD');
INSERT INTO travel_documents_details(DOCUMENT_ID,DOCUMENT_TYPE ,DOCUMENT_NAME
 ) VALUES (sequ_travel_document_details.NEXTVAL,'PDF','VOTER ID');
INSERT INTO travel_documents_details(DOCUMENT_ID,DOCUMENT_TYPE ,DOCUMENT_NAME
 ) VALUES (sequ_travel_document_details.NEXTVAL,'DOC','ADHAR CARD');
 -----------------------------------------------------------------
 CREATE TABLE TRAVELLING_REQUEST_DETAILS(
TRAVEL_REQUEST_ID NUMBER(20) ,
TRAVEL_DEPARTURE_DATE DATE,
TRAVEL_RETURN_DATE DATE,
TRAVEL_REASON VARCHAR(50),
TRAVEL_MODE VARCHAR(20),
TRAVEL_STATUS VARCHAR(50) DEFAULT 'PENDING',
PROJECT_MANAGER_STATUS VARCHAR(50) DEFAULT 'PENDING',
DIRECTOR_STATUS VARCHAR(50) DEFAULT 'PENDING',
EMPLOYEE_ID NUMBER(10),
TRAVEL_LOCATION VARCHAR(20),
TRAVEL_DETAILS_ID NUMBER(10),
DOCUMENT_ID NUMBER(10),
CONSTRAINT PK_TRAVEL_REQUEST_ID PRIMARY KEY(TRAVEL_REQUEST_ID),
CONSTRAINT FK_DOCUMENT_ID FOREIGN KEY(DOCUMENT_ID)
REFERENCES TRAVEL_DOCUMENTS_DETAILS(DOCUMENT_ID),
CONSTRAINT FK_TRAVEL_DETAILS_ID FOREIGN KEY(TRAVEL_DETAILS_ID)
REFERENCES TRAVELLING_DETAILS(TRAVEL_DETAILS_ID),
CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEE_DETAILS(EMPLOYEE_ID)
);
CREATE SEQUENCE seq_travelling_request_details INCREMENT by 1 Start with 900;
drop SEQUENCE seq_travelling_request_details;
INSERT INTO travelling_request_details(TRAVEL_REQUEST_ID,TRAVEL_DEPARTURE_DATE,TRAVEL_RETURN_DATE
,TRAVEL_REASON ,TRAVEL_MODE ,TRAVEL_STATUS ,PROJECT_MANAGER_STATUS ,DIRECTOR_STATUS ,
EMPLOYEE_ID,TRAVEL_LOCATION ,TRAVEL_DETAILS_ID , DOCUMENT_ID )
VALUES (seq_travelling_request_details.NEXTVAL,TO_DATE('24-Jan-2022','DD-MM-YYYY'),TO_DATE('30-Jan-2022','DD-MM-YYYY'),
'BUISSNESS PERPUSE','FLIGHT','PENDING','PENDING','PENDING',501,'CHENNAI',800,700);

INSERT INTO travelling_request_details(TRAVEL_REQUEST_ID,TRAVEL_DEPARTURE_DATE,TRAVEL_RETURN_DATE
,TRAVEL_REASON ,TRAVEL_MODE ,TRAVEL_STATUS ,PROJECT_MANAGER_STATUS ,DIRECTOR_STATUS ,
EMPLOYEE_ID,TRAVEL_LOCATION ,TRAVEL_DETAILS_ID , DOCUMENT_ID )
VALUES (seq_travelling_request_details.NEXTVAL,TO_DATE('12-Jan-2022','DD-MM-YYYY'),TO_DATE('16-Jan-2022','DD-MM-YYYY'),
'BUISSNESS PERPUSE','TRAIN','PENDING','PENDING','PENDING',502,'CHENNAI',801,701);
----------------------------
------------------------------------------------------------------
SELECT * FROM LOGIN_DETAILS;
SELECT * FROM employee_details;
SELECT * FROM slab_master;
SELECT * FROM TRAVEL_AGENT_DETAILS;
SELECT * FROM travelling_request_details;
SELECT * FROM TRAVELLING_DETAILS;
SELECT * FROM travel_documents_details;
--------------------------------------------------------------------------
DROP TABLE LOGIN_DETAILS;
DROP TABLE employee_details;
DROP TABLE slab_master;
DROP TABLE travelling_request_details;
DROP TABLE TRAVELLING_DETAILS;
DROP TABLE travel_documents_details;
drop table TRAVEL_AGENT_DETAILS;
--------------------------------------------------------------------------------
create sequence mysequence start with 1 increment by 1;

create table temp ( id number(10) , name varchar(20));

insert into temp values(mysequence.nextVal , 'A');

select * from temp;

drop sequence mysequence;


---------------------------------------------------------------
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER employeetravel IDENTIFIED BY employeetravel;

GRANT CONNECT ,DBA TO employeetravel;